version: '3'

services:
  gameframe-authservice:
    build: .
    container_name: gameframe-authservice
    ports:
      - "8070:8070"
    expose:
      - "8070/tcp"
    networks:
      - gameframe-internal-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  gameframe-internal-network:
    external: true
